# .gitpod.yml
image:
  file: .gitpod.Dockerfile

tasks:
  - init: pip install -r requirements.txt
    command: mitmdump -s conductor_proxy.py -p 8080

ports:
  - port: 8080
    onOpen: open-preview

github:
  prebuilds:
    # Enable prebuilds for all branches
    master: true
    branches: true
    pullRequests: true

vscode:
  extensions:
    - ms-python.python
    - eamodio.gitlens
